package com.example.braileapp

class Caracter(val caracter: String, val codigo: String)


fun loadCaracteresList(): List<Caracter> {

    var mutableListCaracter = mutableListOf<Caracter>()
    mutableListCaracter.add(Caracter("a","1"))
    mutableListCaracter.add(Caracter("b","12"))
    mutableListCaracter.add(Caracter("c","14"))
    mutableListCaracter.add(Caracter("d","145"))
    mutableListCaracter.add(Caracter("e","15"))
    mutableListCaracter.add(Caracter("f","124"))
    mutableListCaracter.add(Caracter("g","1245"))
    mutableListCaracter.add(Caracter("h","125"))
    mutableListCaracter.add(Caracter("i","24"))
    mutableListCaracter.add(Caracter("j","245"))
    mutableListCaracter.add(Caracter("k","13"))
    mutableListCaracter.add(Caracter("l","123"))
    mutableListCaracter.add(Caracter("m","134"))
    mutableListCaracter.add(Caracter("n","1345"))
    mutableListCaracter.add(Caracter("ñ","12456"))
    mutableListCaracter.add(Caracter("o","135"))
    mutableListCaracter.add(Caracter("p","1234"))
    mutableListCaracter.add(Caracter("q","12345"))
    mutableListCaracter.add(Caracter("r","1235"))
    mutableListCaracter.add(Caracter("s","234"))
    mutableListCaracter.add(Caracter("t","2345"))
    mutableListCaracter.add(Caracter("u","136"))
    mutableListCaracter.add(Caracter("v","1236"))
    mutableListCaracter.add(Caracter("w","2456"))
    mutableListCaracter.add(Caracter("x","1346"))
    mutableListCaracter.add(Caracter("y","13456"))
    mutableListCaracter.add(Caracter("z","1356"))
    mutableListCaracter.add(Caracter("1","1"))
    mutableListCaracter.add(Caracter("2","12"))
    mutableListCaracter.add(Caracter("3","14"))
    mutableListCaracter.add(Caracter("4","145"))
    mutableListCaracter.add(Caracter("5","15"))
    mutableListCaracter.add(Caracter("6","124"))
    mutableListCaracter.add(Caracter("7","1245"))
    mutableListCaracter.add(Caracter("8","125"))
    mutableListCaracter.add(Caracter("9","24"))
    mutableListCaracter.add(Caracter("0","245"))
    mutableListCaracter.add(Caracter("num","3456"))
    mutableListCaracter.add(Caracter("mayu","46"))
    mutableListCaracter.add(Caracter("á","12356"))
    mutableListCaracter.add(Caracter("é","2346"))
    mutableListCaracter.add(Caracter("í","34"))
    mutableListCaracter.add(Caracter("ó","346"))
    mutableListCaracter.add(Caracter("ú","23456"))
    mutableListCaracter.add(Caracter("_","36"))
    mutableListCaracter.add(Caracter(")","2"))
    mutableListCaracter.add(Caracter(";","23"))
    mutableListCaracter.add(Caracter(":","25"))
    mutableListCaracter.add(Caracter(".","3"))
    mutableListCaracter.add(Caracter("(","126"))
    mutableListCaracter.add(Caracter(")","453"))
    mutableListCaracter.add(Caracter("“","236"))
    mutableListCaracter.add(Caracter("¿?","26"))
    mutableListCaracter.add(Caracter("¡!","235"))

    return mutableListCaracter.toList()
}
